# Created using wingetcreate 0.5.0.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: UnityTechnologiesInc.UnityHub
PackageVersion: 3.0.1
PackageLocale: en-US
Publisher: Unity Technologies Inc.
PackageName: Unity Hub
License: Copyright © 2022 Unity Technologies Inc.
ShortDescription: The Official Unity Hub
ManifestType: defaultLocale
ManifestVersion: 1.1.0

